require:
  - rubocop-rake
  - rubocop-rspec  # if using RSpec

AllCops:
  TargetRubyVersion: 3.0  # specify your minimum Ruby version
  NewCops: enable
  SuggestExtensions: false

# Common gem settings
Gemspec/RequiredRubyVersion:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "spec/**/*"
