name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
    
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Update Release PR
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GHA_WRITE_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundle-cache: true
          ruby-version: '3.0'
        if: ${{ steps.release.outputs.release_created }}
      - name: Bundle Install
        run: bundle install
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish to GitHub
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GHA_WRITE_TOKEN}}"
          OWNER: ${{ github.repository_owner }}
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{ secrets.RUBYGEMS_AUTH_TOKEN }}"
        if: ${{ steps.release.outputs.release_created }}
